### ISSUE TITLE
webgpu cts not run when ubunt + Discrete graphics card.

### ISSUE THREAD

**Issue by 82157402** [gpuweb/cts#3783] opened 2024-06-07 09:00 UTC
i try to run webpug cts, But it only can run with swiftshader, not my gpu card.
![image](https://github.com/gpuweb/cts/assets/12945580/b74eee41-c7c9-4c3b-a8ae-86237aed6a8e)
I check chrome://gpu. It show normal.
![image](https://github.com/gpuweb/cts/assets/12945580/7868e6b8-c1a9-4140-99ff-cd9038fd0488)
![image](https://github.com/gpuweb/cts/assets/12945580/1506bb07-2298-4ab2-859c-cc99bb12ac8d)
 
who can help me？Thanks!

**Comment by kainino0x** [comment] 2024-06-07 21:45
This probably is caused by one of the various reasons Chrome does not yet fully support WebGPU on Linux. For example your Vulkan driver may be missing some extension that we need for Dawn-Chromium integration.

It would be easier to help if you can share your full chrome://gpu (as a text file).

**Comment by 82157402** [comment] 2024-06-11 01:28
Please
[about-gpu-2024-06-11T01-20-28-661Z.txt](https://github.com/user-attachments/files/15780805/about-gpu-2024-06-11T01-20-28-661Z.txt)

how to check missing some extension?

**Comment by 82157402** [comment] 2024-06-11 01:29
Please
[about-gpu-2024-06-11T01-20-28-661Z.txt](https://github.com/user-attachments/files/15780837/about-gpu-2024-06-11T01-20-28-661Z.txt)

How to check  missing some extension?

**Comment by kainino0x** [comment] 2024-06-11 03:02
Thanks for that, for others' reference here are the flags:
`--enable-unsafe-webgpu --enable-features=Vulkan`
and here is the GPU:
`<Discrete GPU>  Vulkan backend - NVIDIA GeForce GTX 1660 SUPER`

I think this is the problem: In the OpenGL section, it says
`GPU0                            : VENDOR= 0x1ed5 [Google Inc. (MOORE THREADS)], DEVICE=0x0201 [ANGLE (MOORE THREADS, MTT Mesa, OpenGL 4.1 build 20240611 debug develop beb22e488@20240608 )], DRIVER_VENDOR=MOORE THREADS, DRIVER_VERSION=4.1 *ACTIVE*`

I think Chromium requires OpenGL (for legacy stuff) and Vulkan (for WebGPU) to be running on the same device. But maybe this MOORE THREADS device doesn't have Vulkan support.

I think this could be fixed by passing some flag telling Chromium not to use OpenGL at all, could you try adding `--use-angle=vulkan` and see if that helps? I am not sure if that will actually convince Chromium to use the NVIDIA GPU or not though.

**Comment by greggman** [comment] 2024-06-27 23:58
This is the wrong forum for chrome issues. It seems like this issue should argubuably be closed and deleted.

**Comment by kainino0x** [comment] 2024-06-28 02:03
Let's go ahead and close this. Reporter, please start a thread on Dawn's mailing list or Matrix chat (see https://dawn.googlesource.com/dawn/+/refs/heads/main/README.md) if the tips above don't help. You can file a bug on crbug.com if there seems to be a Dawn or Chromium bug.

**Closed by kainino0x** 2024-06-28 02:03 UTC
