### ISSUE TITLE
`fullF32Range` has expectation that looks suspicious

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/cts#1971] opened 2022-11-04 16:26 UTC
`fullF32Range()` says that it `returns an ascending sorted array of numbers spread over the entire range of 32-bit floats`

AFAICT the constants in `src/webgpu/util/constants.ts` declare `min` to be numerically smaller than `max`.

The final test case of `fullF32Range()`
https://github.com/gpuweb/cts/blob/02f4683004a9f2a736f024d7f7477463f2ca6a21/src/unittests/maths.spec.ts#L751

Has the list of expectations:

0: `kValue.f32.negative.min`
1: `kValue.f32.negative.max`
2: `kValue.f32.subnormal.negative.max`
3: `kValue.f32.subnormal.negative.min`
4: `0.0`
5: `kValue.f32.subnormal.positive.min`
6: `kValue.f32.subnormal.positive.max`
7: `kValue.f32.positive.min`
8: `kValue.f32.positive.max`

2 and 3 look like they're around the wrong way?

**Comment by zoddicus** [comment] 2022-11-07 18:21
The root cause of this is that the withinULP, and related functions, were not passing down whether or not to flush values, so the ULP was being calculated assuming FTZ is valid. This is the correct behaviour for the vast majority of cases, expect when we want to be differentiating between subnormal values like in this test. I have a fix for this written, just need to add some test coverage.

**Closed** 2022-11-08 18:54 UTC
Labels: bug, wgsl
