### ISSUE TITLE
test builtins and expressions in all shader stages

### ISSUE THREAD

**Issue by dneto0** [gpuweb/cts#841] opened 2021-11-18 15:52 UTC
Currently the builtins tests only exercise compute shaders.
The other shader stages should be tested as well.

Also, some builtins/constructs are only available in certain stages. E.g. the derivatives are only available in fragment shaders.

**Comment by jrprice** [comment] 2024-01-22 18:14
Duplicate of #2294.

**Closed by jrprice** 2024-01-22 18:14 UTC
Labels: wgsl
