### ISSUE TITLE
wgsl: test unrestricted_pointer_parameters WGSL language extension

### ISSUE THREAD

**Issue by dneto0** [gpuweb/cts#3181] opened 2023-11-20 22:05 UTC
https://github.com/gpuweb/gpuweb/pull/4312  has landed

**Comment by dneto0** [comment] 2023-11-20 22:15
It's a language extension, so this is blocked https://github.com/gpuweb/cts/issues/3057

**Comment by ben-clayton** [comment] 2024-01-11 21:45
Duplicate of https://github.com/gpuweb/cts/issues/3056

**Closed by ben-clayton** 2024-01-11 21:45 UTC
Labels: wgsl
